AdminPanel.Web/Controllers/ChatController.cs
using AdminPanel.Domain.Entities;
using AdminPanel.Repository.Repositories;
using AdminPanel.Repository.Repositories.Filters;
using AdminPanel.Repository.Repositories.Interfaces;
using AdminPanel.Web.Controllers.Base;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Telegram.Bot;
using AdminPanel.TelegramBot;
using Polly;
using Microsoft.Extensions.DependencyInjection;
using System;

namespace AdminPanel.Web.Controllers
{
    [Authorize]
    public class ChatController : BaseAuthController
    {
        private readonly IChatRepository<Message> _chatRepository;
        private readonly IUserRepository _userRepository;

        public ChatController(IChatRepository<Message> chatRepository, IUserRepository userRepository)
        {
            _chatRepository = chatRepository;
            _userRepository = userRepository;
        }

        [HttpGet]
        public IActionResult Message()
        {
            ViewBag.AllMessages = _chatRepository.GetAllMessages();
            return View(_chatRepository.Create());
        }

        [HttpPost]
        public async Task<IActionResult> Message(string message, CancellationToken cancellationToken)
        {
            if (ModelState.IsValid)
            {
                await _chatRepository.UpdateAsync(message, UserId, cancellationToken);

                //TODO 
                var mes = _chatRepository.GetAllMessages().Last();
                var chatId = (long)_userRepository.FindOrCreate(UserId).ChatId;


                if (chatId != null)
                {
                    await AdminPanel.TelegramBot.TelegramBot.SendMessageAsync(cancellationToken, mes, chatId);
                }
            }
            return Ok();
        }
    }
}

AdminPanel.Web/Controllers/NewsController.cs
using AdminPanel.Domain.Entities;
using AdminPanel.Repository.Repositories;
using AdminPanel.Repository.Repositories.Filters;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Data;
using AdminPanel.Domain.Enums;
using AdminPanel.Web.Controllers.Base;

namespace AdminPanel.Web.Controllers
{
    [Authorize]
    public class NewsController : BaseAuthController
    {
        private readonly INewsRepository newsRepository;

        public NewsController(INewsRepository newsRepository)
        {
            this.newsRepository = newsRepository;
        }

        [AllowAnonymous]
        [HttpGet]
        public JsonResult GetData(NewsFilter newsFilter)
        {
            var news = newsRepository.All(newsFilter);

            return Json(news);
        }

        [AllowAnonymous]
        [HttpGet]
        public IActionResult Index()
        {
            ViewBag.News = newsRepository.GetAllNews();
            return View();
        }

        [HttpGet]
        public IActionResult IndexGrid()    
        {
            return View();
        }

        [Authorize(Roles = "Администратор")]
        [HttpGet]
        public IActionResult Edit(int? id)
        {
            return View(newsRepository.FindOrCreate(id));
        }

        [Authorize(Roles = "Администратор")]
        [HttpPost]
        public async Task<IActionResult> Edit(News news, CancellationToken cancellationToken)
        {
            if (ModelState.IsValid)
            {
                await newsRepository.UpdateAsync(news, cancellationToken);
                return RedirectToAction("Index");
            }
            return View(news);
        }

    }
}

AdminPanel.Web/Controllers/ProfileController.cs
using AdminPanel.Domain.Entities;
using AdminPanel.Repository.Repositories;
using AdminPanel.Repository.Repositories.Filters;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Data;
using AdminPanel.Domain.Enums;
using AdminPanel.Web.Controllers.Base;
using System.IO;
using System.Security.Claims;
using AdminPanel.Domain.helpers;
using Azure.Core;
using static System.Net.WebRequestMethods;
using Microsoft.AspNetCore.StaticFiles;
using Dadata.Model;
using Microsoft.AspNetCore.Mvc.Filters;
using System.Reflection;
using AdminPanel.Web.Services;

namespace AdminPanel.Web.Controllers
{
    [Authorize]
    public class ProfileController : BaseAuthController
    {
        private IWebHostEnvironment _hostEnv;
        private IImageRepository _imageRepository;
        private IImageService _imageService;
        public ProfileController(IWebHostEnvironment hostEnv, IImageRepository imageRepository, IImageService imageService)
        {
            _hostEnv = hostEnv;
            _imageRepository = imageRepository;
            _imageService = imageService;
        }

        [AllowAnonymous]
        public override void OnActionExecuting(ActionExecutingContext context)
        {
            if (context.HttpContext.User.Identity.IsAuthenticated)
            {
                var userRepository = context.HttpContext.RequestServices.GetService<IUserRepository>();

                var user = userRepository.FindOrCreate(UserId);

                ViewBag.User = user;
            }
        }

        [HttpPost]
        public async Task<IActionResult> Upload(IFormFile file, CancellationToken cancellationToken)
        {
            if (file != null)
            {
                var path = _imageService.GeneratePath(UserId.ToString(), file.FileName);

                await using (var fileStream = new FileStream(Path.GetFullPath(path), FileMode.Create))
                {
                    await file.CopyToAsync(fileStream);
                }

                var image = new Image { Name = file.FileName, Path = path, 
                    Hash = HashHelper.Hash(file.FileName), ContentType = file.ContentType};
                await _imageRepository.UpdateAvatar(image, UserId, cancellationToken);
            }
            return RedirectToAction("Index");   
        }

        public IActionResult Index()
        {
            return View("Index");
        }
    }
}

AdminPanel.Web/Controllers/UsersController.cs
using System.Security.Claims;
using AdminPanel.Domain.Entities;
using AdminPanel.Repository.Repositories;
using Microsoft.AspNetCore.Mvc;
using AdminPanel.Repository.Repositories.Filters;
using AdminPanel.Web.Controllers.Base;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authorization;


namespace AdminPanel.Web.Controllers
{
    [Authorize]
    public class UsersController : BaseAuthController
    {
        private readonly IUserRepository userRepository;
        private readonly IRoleRepository roleRepository;
        private readonly IProjectRepository projectRepository;
        private readonly IUserProjectRepository userProjectRepository;
        public UsersController(IRoleRepository roleRepository, IUserRepository userRepository, IProjectRepository projectRepository, IUserProjectRepository userProjectRepository)
        {
            this.roleRepository = roleRepository;
            this.userRepository = userRepository;
            this.projectRepository = projectRepository;
            this.userProjectRepository = userProjectRepository;
        }

        [AllowAnonymous]
        [HttpGet]
        public JsonResult GetData(UserFilter userFilter)
        {
            var users = userRepository.All(userFilter);

            return Json(users);
        }

        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult Edit(int? id)
        {
            InitUserSelects();
            return View(userRepository.FindOrCreate(id));
        }

        [HttpPost]
        public async Task<IActionResult> Edit(User user, CancellationToken cancellationToken)
        {
            InitUserSelects();
            if (ModelState.IsValid)
            {    
                await userRepository.UpdateAsync(user, cancellationToken);

                Authorize(user);

                return RedirectToAction("Index");

            }
            return View(user);
        }

        [HttpDelete]
        public async Task Delete(int id, CancellationToken cancellationToken)
        { 
            await userRepository.DeleteAsync(id,cancellationToken);
        }

        [AllowAnonymous]
        [HttpPost]
        [HttpGet]
        public  IActionResult CheckExistingEmail(int id, string email)
        {
            if (userRepository.Find(id, email))
            {
                return Json($"Почтовый адрес {email} уже используется");
            }
            return Json(true);
        }

        [NonAction]
        public void InitUserSelects()
        {
            ViewBag.Roles = roleRepository.GetAllRoles();
            ViewBag.Projects = projectRepository.GetAllProjects();
        }
    }
}

AdminPanel.Web/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Authorization
@using AdminPanel.Domain.Entities
@inject IAuthorizationService AuthorizationService



<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Панель Администратора</title>
    
    

    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/lib/sweetalert2/sweetalert2.css"/>
    <link rel="stylesheet" href="~/lib/Foundation/css/foundation.css"/>
    <script src="~/lib/moment/moment-with-locales.min.js"></script>
    <script src="~/lib/moment/moment.js"></script>
    <script src="~/js/main.js" asp-append-version="true"></script>
    <script src="~/lib/sweetalert2/swal-api.js"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    
    <script src="https://cdn.tiny.cloud/1/f9mc8r9ivjy5i6cawjl7dqbwx3njcx378yig9t50qs3waqbg/tinymce/6/tinymce.min.js" referrerpolicy="origin"></script>
    
    

    

</head>
<body>
<div class="window-size">

    <header class="p-3 bg-light">
        <div class="container">
            <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
                <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
                    <li>
                        <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Главная</a>
                    </li>
                    <li>
                        <a class="navbar-brand" asp-area="" asp-controller="Users" asp-action="Index">Пользователи</a>
                    </li>
                    <li>
                        <a class="navbar-brand" asp-area="" asp-controller="News" asp-action="Index">Новости</a>
                    </li>
                    <li>
                        <a class="navbar-brand" asp-area="" asp-controller="Chat" asp-action="Message">Чат</a>
                    </li>
                </ul>

                <div class="row">
                    @if (User.Identity.IsAuthenticated)
                    {
                        <div class="col p-0">
                            <img src=@Url.RouteUrl(new {Controller = "Image", Action = "Index", hash = @ViewBag.ImageHash})
                                class="round cropped"/>
                        </div>
                        
                        <div class="dropdown col" id="profile">
                            <a  class="dropdown-toggle" data-bs-toggle="dropdown">@User.Identity.Name</a>
                            <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                                <li><a class="dropdown-item" asp-controller="Profile" asp-action="Index">Мой аккаунт</a></li>
                                <li><a class="me-2 dropdown-item" asp-area="" asp-controller="Account" asp-action="Logout">Выйти</a></li>
                            </ul>
                        </div>
                    }
                    else
                    {
                        <a class="me-2" asp-area="" asp-controller="Account" asp-action="Login">Войти</a>
                    }
                </div>
            </div>
        </div>
    </header>

    <div class="container-fluid">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
</div>
    <footer class="p-2 myfooter bg-light social-footer">
    <div class="container">
        <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
            <div class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
            &copy; @DateTime.Now.Year - Новостной портал
            </div>

            <div class="social-footer-icons">
                <ul class="menu simple">
                    <li><a href="https://www.facebook.com/"><i class="fa fa-facebook" aria-hidden="true"></i></a></li>
                    <li><a href="https://www.instagram.com/?hl=en"><i class="fa fa-instagram" aria-hidden="true"></i></a></li>
                    <li><a href="https://www.pinterest.com/"><i class="fa fa-pinterest-p" aria-hidden="true"></i></a></li>
                    <li><a href="https://twitter.com/?lang=en"><i class="fa fa-twitter" aria-hidden="true"></i></a></li>
                </ul>
            </div>
        </div>
    </div>
</footer>

    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/lib/sweetalert2/sweetalert2.all.js"></script>
<script src="~/lib/sweetalert2/324dccf590.js" crossorigin="anonymous"></script>

<script src="~/lib/agGrid/agGrid-locale/locale.ru.js"></script>
@*<script src="~/lib/TinyMCE/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>*@
<script src="~/lib/Foundation/app.js"></script>
<script src="~/lib/Foundation/vendor/foundation.js"></script>
<script src="~/lib/Foundation/vendor/what-input.js"></script>

<script src="~/lib/jquery/dist/jquery.js"></script>
    <script type="text/javascript" src="~/lib/jquery-SerializeToJSON/jquery.serializeToJSON.js"></script>

<script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
<script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
<script type="text/javascript" src="~/lib/jquery/dist/messages_ru.js"></script>

@await RenderSectionAsync("Scripts", required: false)

</body>
</html>